version: 0.2

phases:
  pre_build:
    commands:
      echo "Preparing deployment phase..."
  build:
    commands:
      echo "Syncing build artifacts to S3 hosting bucket..."
      # Replace your-bucket-name dynamically or hardcode it matching the terraform output
      aws s3 sync . s3://${WEB_BUCKET_NAME} --delete --exclude "main.tf" --exclude ".terraform*" --exclude "terraform.tfstate*"
artifacts:
  files:
    - '**/*'